# ----------- CONFIGURABLE START -----------
title:            "Sam Showalter's Blog"
description:      "Just some nonsense"
url:              https://samshowalterblog.github.io 
signoff:          "Samuel Showalter" # Your name
#google_analytics: UA-101222464-1
share:            true 

paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Books
    url:          /book
    external:     false
  - name:         Road
    url:          /road
    external:     false
  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
