# ----------- CONFIGURABLE START -----------
title:            "Sam Showalter's Blog"
description:      "The thoughts of a non-traditional PhD Student"
url:              https://samshowalterblog.github.io 
signoff:          "Sam Showalter" # Your name
#share:            true 

paginate: 9
paginate_path: "showalterpage:num"
gems: [jekyll-paginate]
links:
  - name:         Posts
    url:          /
    external:     false
  - name:         Archive
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          https://samshowalter.github.io/#blog
    external:     true
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto-ids: true
  syntax_highlighter: rouge

defaults:
  - values:
      layout: "default"
