# ----------- CONFIGURABLE START -----------
title:            "Sam Showalter's Blog"
description:      "My Blog"
url:              https://samshowalterblog.github.io # 域名
signoff:          "Sam Showalter" # Your name
facebook_appid:   #liberxue
#google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Books
    url:          /book
    external:     false
  - name:         Road
    url:          /road
    external:     false
  - name:         Archive
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
