# ----------- CONFIGURABLE START -----------
title:            "Sam Showalter's Blog"
description:      "My Blog"
url:              https://samshowalterblog.github.io # 域名
signoff:          "Sam Showalter" # Your name
#share:            true 

paginate: 15
paginate_path: "showalterpage:num"
gems: [jekyll-paginate]
links:
  - name:         Posts
    url:          /
    external:     false
  - name:         Archive
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          https://samshowalter.github.io
    external:     true
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
